import "./globals.css";
import { Inter } from "next/font/google";
import { Web3Provider } from "@/components/Web3Provider";
import * as React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Web3Provider>
          <main className="flex flex-col items-center p-24">{children}</main>
        </Web3Provider>
      </body>
    </html>
  );
}
